### ISSUE TITLE
LibreSignal

### ISSUE THREAD

**Issue by ghost** [JavaJens/TextSecure#39] opened 2015-10-06 12:06 UTC
So I noticed LibreText is now LibreSignal.
Can someone clarify?
The play store version does not seem to be renamed to signal yet. And calling doesn't work either yet. So what's up whit this update?

**Comment by JavaJens** [comment] 2015-10-06 12:08
RedPhone has been merged into the main version. However it is currently only in Beta.
Regarding this fork, RedPhone capabilities have been disabled until there is time available to figure out if/how calling works without GCM.

**Closed as completed by JavaJens** 2015-10-06 12:08 UTC

**Comment by xmikos** [comment] 2015-10-06 15:09
@JasperWeiss if you use builds of LibreSignal from my main repository (not WebSocket-fork, which is in my experimental repository), calling should work. But according to issue [#4181](https://github.com/WhisperSystems/TextSecure/issues/4181) you can't call people who are still using old RedPhone. (Libre)Signal will not offer you encrypted calls with them, but they will see you as using RedPhone and can call you (I have tested it).

Strange is that they can even call you if you are using this WebSocket-fork which according to @f41c0r and @JavaJens shouldn't work. I didn't have time to test it more thoroughly how is this possible...

**Comment by ghost** [comment] 2015-10-06 16:14
@xmikos I'll get the main repository then and do some testing. I'll also check if someone can call me if I'm on websocket. Just for the fun of it
Anything else I can help with?

**Comment by ghost** [comment] 2015-10-06 16:23
Also, Just noticed something. It may just be me, but LibreSignal is draining my battery A LOT. According to android battery statistics it uses 16%. My phone used to be at about 20% at the end of the day, now it's empty just before dinner.

**Comment by xmikos** [comment] 2015-10-06 16:27
I don't see bigger battery drain on my device (Nexus 4).

**Comment by paride** [comment] 2015-10-06 16:32
FYI: moxie wrote something about implementing WebSockets on Android M:

https://lists.riseup.net/www/arc/whispersystems/2015-10/msg00016.html

also interesting:

https://lists.riseup.net/www/arc/whispersystems/2015-10/msg00017.html

**Comment by xmikos** [comment] 2015-10-07 08:55
Just FYI: It is intended behavior that you can't call old RedPhone users with new Signal, see this post by Moxie:

https://lists.riseup.net/www/arc/whispersystems/2015-10/msg00001.html

```
2) Within Signal, you will only be able to initiate calls to other
Signal users (either on Android or iOS).  You will be able to receive
calls from legacy RedPhone users, but not initiate calls to them.
```

When Signal gets out of beta, RedPhone should be updated with prompt for a migration over to Signal.
